include ../vsn.mk

include ../../../support/include.mk

ERLC_FLAGS += -I ../../fm_basic/include

all: $(ERL_OBJECTS) $(ERL_DOCUMENTS) # ../ebin/fm_clients.app
#all: $(ERL_OBJECTS) ../ebin/fm_clients.app

clean:
	-rm $(ERL_OBJECTS)

